### PR TITLE
WebPage for Java logging frameworks

### PR DESCRIPTION
**Pull request by PratikshaPatil77**

### CODE REVIEW

**Comment by PratikshaPatil77** [comment]
@nbhavana @sonamgupta21 PR is ready for review. Please have a look. And let me know if any changes required.

**Review by nbhavana — COMMENTED** [review]
The text is not aligned. The table is also cutoff.
image
image

**Review by nbhavana — COMMENTED** [review]
The cutting off issue is till not fixed.

**Comment by PratikshaPatil77** [comment]
@nbhavana @sonamgupta21 

Changes are ready to review. 
Please have a look and let me know if any other changes required.

**Review by nbhavana — COMMENTED** [review]
lgtm, @sonamgupta21 take a look and if its looks ok to you, you can approve it.

**Review by sonamgupta21 — APPROVED** [review]

**Pull request merged**
