### PR TITLE
feat: Add RSS Feed

### PR DESCRIPTION
**Pull request by Macbeth98**
# Description

- Adds RSS Feed to the SigLens Website.
- Added the RSS XML link beside the Social URLs on the main page and all the blog pages.

##Note:
- The dates I have mentioned in the XML file are arbitrary since I could not find the publishing date on the Blog. 
- The descriptions mostly are the first one or two paragraphs from the blogs.
- Let me know of any changes.

### CODE REVIEW

**Comment by Macbeth98** [comment]
The Netlify version is here: https://siglens-web.netlify.app/

**Comment by nkunal** [comment]
@sonamgupta21 @AndrewHess  can you review this

**Review by AndrewHess — COMMENTED** [review]
This looks good to me. A lot of the html changes you have are are just formatting; do we want to include these in the PR? What do you think @sonamgupta21?

**Comment by sonamgupta21** [comment]
> This looks good to me. A lot of the html changes you have are are just formatting; do we want to include these in the PR? What do you think @sonamgupta21?

I think it's fine, most of the changes are due to adding the RSS icon in the footer.

**Review by AndrewHess — APPROVED** [review]

**Pull request merged**
