### PR TITLE
webPage for Guide:ElasticSearch

### PR DESCRIPTION
**Pull request by PratikshaPatil77**
First HTML page for GUIDE: Elasticsearch: Indexes, replicas and management.

### CODE REVIEW

**Review by nbhavana — COMMENTED** [review]
There are few things that don't work:
1. The heading should be fixed.
2. Change the back ground color to this rgba(241,250,255,.8)
3. The content does not cover the whole screen when you are on big screen.
4. The heading and nav bar are messed up on big screen and on mobile
image
SigScalr  Elastic Indexes, replicas, management

**Review by sonamgupta21 — COMMENTED** [review]
Padding for navbar and footer should be same as the other screens.

**Comment by sonamgupta21** [comment]
@nbhavana, why are we sticking the heading at the top? In mobile view, the content area becomes less because of that, and in the end, it also overlaps the footer.
image
image

**Comment by nbhavana** [comment]
> @nbhavana, why are we sticking the heading at the top? In mobile view, the content area becomes less because of that, and in the end, it also overlaps the footer. image image
That was something I thought will look nice. But if  it messes with the content area we can remove the fixed heading.

**Comment by PratikshaPatil77** [comment]
@sonamgupta21 @nbhavana  PR is ready for review. Please have look and let me know if any changes required.

**Comment by sonamgupta21** [comment]
The mobile view is not coming correctly.

image

**Comment by PratikshaPatil77** [comment]
@sonamgupta21 Is it Ok now 
Screenshot 2024-01-05 at 12 36 31 PM

**Comment by PratikshaPatil77** [comment]
Also for Heading

**Comment by PratikshaPatil77** [comment]
And for main heading 
Screenshot 2024-01-05 at 12 40 08 PM

**Comment by PratikshaPatil77** [comment]
@sonamgupta21 Please have a look on the page and let me know if any changes required.

**Review by sonamgupta21 — COMMENTED** [review]
Lgtm.

**Review by nbhavana — COMMENTED** [review]
lgtm.
There are few nit picks about naming:
1. Change the `guide` folder name to `guides`.
2. Rename `guide.css` to `guides.css`
3. Rename `guide.js` to `guides.js`
Make sure you update the references of this files are also updated after you rename.
The navbar is not covering the whole width on mobile view, if its a quick fix, do it in this PR or if its taking long, you can take care it in next PR

**Comment by PratikshaPatil77** [comment]
@nbhavana changes are done.

**Review by nbhavana — APPROVED** [review]

**Pull request merged**
