### PR TITLE
webPage for .Net

### PR DESCRIPTION
**Pull request by PratikshaPatil77**

### CODE REVIEW

**Comment by PratikshaPatil77** [comment]
@nbhavana @sonamgupta21
 PR is ready for review . Please have a look.

**Review by sonamgupta21 — COMMENTED** [review]
image
image

Increase the width of these tables.

**Comment by PratikshaPatil77** [comment]
@sonamgupta21 @nbhavana 
Changes are ready for review.

**Review by nbhavana — COMMENTED** [review]
The code block boxes are not looking neat, they are bleeding all the way to right. Make it look same as the other guides pages merged before.
image

**Comment by PratikshaPatil77** [comment]
@sonamgupta21 @nbhavana 
PR is ready for review. You can have a look.

**Review by sonamgupta21 — APPROVED** [review]

**Pull request merged**
